name: vsphere-automation-sdk-python
on: [push]
jobs:
  build:
    runs-on: self-hosted
    container: vmcswaggers-docker-local.artifactory.eng.vmware.com/vsphere-python-testing:1.2
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env: 
           NIMBUS_TESTBED: vapi-testbeds.eng.vmware.com
           VC_PASSWORD: Admin!23
           VC_USER_NAME: administrator@vsphere.local
           VC_VERSION: 67u3
           VC_VERSION_MAIN: main
        run: |
          echo "Running smoke test"
          bash tests/smoke-test.sh -u $VC_USER_NAME -p $VC_PASSWORD
