name: vsphere-automation-sdk-python
on: [push]
jobs:
  build:
    runs-on: self-hosted
    container: vmcswaggers-docker-local.artifactory.eng.vmware.com/vsphere-python-testing:1.2
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env: 
           NIMBUS_TESTBED: ${{ secrets.nimbus_testbed }}
           VC_PASSWORD: ${{ secrets.vc_password }}
           VC_USER_NAME: ${{ secrets.vc_user_name }}
           VC_VERSION: ${{ secrets.vc_version }}
        run: |
          echo "Running smoke test"
          bash tests/smoke-test.sh -u $VC_USER_NAME -p $VM_PASSWORD
